#!/bin/bash

curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
. ~/.nvm/nvm.sh
nvm install 17
nvm alias default 17

sudo ln -s "$(which node)" /usr/bin/node
sudo ln -s "$(which npm)" /usr/bin/npm

export NODE_PATH=$(npm root --quiet -g)


ls $NODE_PATH

npm i -g snarkyjs

ls $NODE_PATH
